#!/bin/bash
set -e



case "$1" in
  configure)
    update-alternatives --install /usr/share/plymouth/themes/default.plymouth default.plymouth /usr/share/plymouth/themes/biglinux-wave/biglinux-wave.plymouth  100
    sed -i 's|^ *\bTheme\b *=.*|Theme=biglinux-wave|' /etc/plymouth/plymouthd.conf
    update-initramfs -u
;;

esac
exit 0
